
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
automation: !include automations.yaml
binary_sensor: !include extras/binary.yaml
camera: !include extras/camera.yaml
conversation:
ffmpeg:
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest
group: !include groups.yaml
homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /share/
    - /tmp/
http: !include extras/http.yaml
input_select: !include extras/input_select.yaml
life360: !include extras/life360.yaml
light: !include lights.yaml
logger: !include extras/logger.yaml
media_extractor: !include extras/extractor.yaml
media_player: !include extras/media.yaml
notify: !include extras/notify.yaml #notificações para celular
recorder: !include extras/recorder.yaml #maria_db
remote: !include extras/remote.yaml #broadlink
scene: !include scenes.yaml
sensor: !include sensors.yaml #bateria, temperatura, umidade, localização, etc
script: !include scripts.yaml
sonoff: !include extras/sonoff.yaml
switch: !include switches.yaml
stream: 
telegram_bot: !include extras/telegram.yaml
tts: !include tts.yaml #text-to-speach
upnp:
websocket_api: